CREATE TABLE IF NOT EXISTS bans (
    id SERIAL NOT NULL PRIMARY KEY,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip VARCHAR NOT NULL,
    reason VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS shares (
    id SERIAL NOT NULL PRIMARY KEY,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    worker_id INT NOT NULL,
    job_diff INT NOT NULL,
    is_valid BOOLEAN NOT NULL
);
